language: python
python:
    - 2.7

services:
    - redis
    - mongodb
    - elasticsearch

virtualenv:
    system_site_packages: true

before_install:
    - sudo apt-get install -qq libevent-dev
    - gem install compass
    - gem install sass
    - gem install sass-rails
    - gem install bootstrap-sass --version 3.1.0.1
    - npm install -g grunt-cli
    - npm install

install:
    - pip install -r requirements.txt

before_script:
    - source travis_before.sh

script:
    - cd www
    - python manage.py test

branches:
  only:
    - master
    - develop

notifications:
  email:
    - maxime@naeka.fr
    - thomas@naeka.fr
    - leo@naeka.fr
  hipchat:
    rooms:
      - secure: "QiuF2g/U6KXckMMwTqWHQvRKrzKdVWGu3M+MeNGK3ZI9DvYjx0vVPhPyFSg3o6X2dWkFD9wEv8S9/ozpmweTTN0JBA8ozjyn8tLfFb5LDg/9EZiJ5QojQapTvtPvrka0ad9tg+gVpNoxyFgFw3uZlSaQQ1/fIDi1KOE+eAzmOyI="
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>)'
    format: html
